from ..core.config import settings

PROJECT_TEMPLATE = {
    "main.py": """from photon import PhotonProject
from router import router

project = PhotonProject()

def main():
    project.listen(router.setup())
""",

    "router.py": """from photon import Router

router = Router()

# ==== AUTO APPS START ====

# ==== AUTO APPS END ====

""",

    "photon_config.py": """
# Auto Generated by Photon CLI
# v.0.0.1 Photon 

DEBUG = True
ENV = "development"
HOST = "127.0.0.1"
PORT = 2117

SECRET_KEY = "photon-key-s3p8-proj=f5d13270-e6e6-4a60-b7e7-71d499811792"

INSTALLED_APPS = []


MIDDLEWARE = []

TEMPLATES = {
    "ENGINE": None,
    "DIRS": [],
    "APP_DIRS": True,
    "AUTOESCAPE": True,
    "OPTIONS": {},
}

STATIC = {
    "URL": "/static/", 
    "DIRS": [], 
    "APP_DIRS": True
}


DATABASES = {}


LOGGING = {
    "LEVEL": "INFO", 
    "FORMAT": "simple", 
    "ACCESS_LOG": True
}

""",
# TODO: change thisss

    "apps/__init__.py": "",
    "manage.py": """
# Photon CLI helper file,
# Auto generated by Photon CLI
# v.0.0.1 Photon

from photon.cli import main
import sys

if __name__ == "__main__":
    main.main(sys.argv)
"""
}
